import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
file1=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\deliveries.csv")
file2=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\matches.csv")
script_dir=os.path.dirname(os.path.abspath(__file__))
save=os.path.join(script_dir,"Graphs_And_Charts")
if not os.path.exists(save):os.makedirs(save)
def Data_Assessment():
    print(file1.dtypes)
    print(file2.dtypes)
    print(file1.head())
    print(file2.head())
    print(file1.isnull().sum()) #Null values present in player_dismissed,dismissal_kind and fielder.
    print(file2.isnull().sum()) #Null values present in city,winner,umpire1,umpire2,umpire3.
    print(file1[file1.duplicated()]) #No Major duplicates out of more than 20000 matches few coincidences can be neglected.
    print(file2[file2.duplicated()]) #No Duplicates at all.
def Match_Analysis():
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    lock=file2["winner"].value_counts().head(14).index
    sns.countplot(data=file2[file2["winner"].isin(lock)],y="winner",hue="winner",order=lock,palette="viridis",legend=False)
    plt.title("IPL Teams That Have Won Most Of The Matches")
    plt.xlabel("No. Of Matches Won")
    plt.ylabel("Team")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Most_Successful_Teams.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    lock1=file2["venue"].value_counts().index
    sns.countplot(data=file2[file2["venue"].isin(lock1)],y="venue",order=lock1,color="darkcyan")
    plt.title("Stadium That Have Hosted Highest No. Of Matches")
    plt.xlabel("No. Of Matches Played")
    plt.ylabel("Stadium")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Top_IPL_Stadiums.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    top7=file2["player_of_match"].value_counts().head(7).index
    sns.countplot(data=file2[file2["player_of_match"].isin(top7)],x="player_of_match",order=top7,color="yellow")
    plt.title("Top 7 Players With Highest No. Of Player Of The Match Titles")
    plt.ylabel("No. Of Times Player Of The Match Awarded")
    plt.xlabel("Player")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Highest_Playerofmatch.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    file2["toss_match_same"] = file2["toss_winner"] == file2["winner"]
    count=file2["toss_winner"].value_counts().head(14).index
    sns.countplot(data=file2[file2["toss_winner"].isin(count)],y="toss_winner",order=count,hue="toss_match_same",palette="mako")
    plt.title("Toss Winner - Match Winner Connection Chart")
    plt.xlabel("No. Of Matches")
    plt.ylabel("Team")
    plt.legend(bbox_to_anchor=(1,0.5),title="Won Both Match And Toss ?",loc="upper left")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Tosswinner-Matchwinner.png"),dpi=300)
    plt.show()
    count1=file2["Season"].value_counts().index
    sns.countplot(data=file2[file2["Season"].isin(count1)],y="Season",order=count1,color="turquoise")
    plt.title("IPL Seasons With Most Matches")
    plt.xlabel("No. Of Matches")
    plt.ylabel("IPL Season")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Top_IPL_Seasons.png"),dpi=300)
    plt.show()
def Batting_Analysis():
    sns.set_style("whitegrid")
    plt.figure(figsize=(10,8))
    top_batsmen = (file1.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).reset_index().head(5))
    sns.barplot(data=(top_batsmen),y="batsman",x="batsman_runs",hue="batsman",palette="viridis")
    plt.title("Top 5 Run Scorers In IPL")
    plt.xlabel("Runs Scored")
    plt.ylabel("Batsman")
    plt.savefig(os.path.join(save,"Top_runscorer.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    file1["sixes"]=file1["batsman_runs"]==6
    six_hitters=(file1.groupby("batsman")["sixes"].sum().sort_values(ascending=False).head(10))
    sns.barplot(data=(six_hitters.reset_index()),y="batsman",x="sixes",hue="batsman",palette="viridis")
    plt.title("Top 10 Six Hitters In IPL")
    plt.xlabel("No. Of Sixes")
    plt.ylabel("Batsman")
    plt.savefig(os.path.join(save,"Top_sixhitters.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    file1["fours"]=file1["batsman_runs"]==4
    four_hitters=(file1.groupby("batsman")["fours"].sum().sort_values(ascending=False).head(10))
    sns.barplot(data=(four_hitters.reset_index()),y="batsman",x="fours",hue="batsman",palette="viridis")
    plt.title("Top 10 Four Hitters In IPL")
    plt.xlabel("No. Of Fours")
    plt.ylabel("Batsman")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Top_Fourhitters.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    topb=file1["batsman"].value_counts().head(10).index
    sns.countplot(data=file1[file1["batsman"].isin(topb)],y="batsman",order=topb,hue="batsman",palette="viridis")
    plt.title("Top 10 Batsman Who Have Faced Highest No. Of Balls In IPL")
    plt.xlabel("NO. Of Balls")
    plt.ylabel("Batsman")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Top_Battsman_Playingmostballs.png"),dpi=300)
    plt.show()
def Bowling_Analysis():
    sns.set_style("whitegrid")
    plt.figure(figsize=(10,8))
    file1["out"]=file1["player_dismissed"]!=np.nan
    Wicket_Takers=(file1.groupby("bowler")["out"].sum().sort_values(ascending=False).head(10))
    sns.barplot(data=(Wicket_Takers.reset_index()),y="bowler",x="out",hue="bowler",palette="viridis")
    plt.title("Top 10 Wicket Takers Of IPL")
    plt.xlabel("Wickets Taken")
    plt.ylabel("Bowler")
    plt.tight_layout()
    plt.savefig(os.path.join(save, "TOP10_Bowlers.png"),dpi=300)
    plt.show()
    top_bowler = (file1.groupby("bowler")["total_runs"].sum().sort_values(ascending=True).reset_index().head(5))
    sns.barplot(data=(top_bowler),y="bowler",x="total_runs",hue="bowler",palette="viridis")
    plt.title("Top 5 Most Economical Bowlers In IPL")
    plt.xlabel("Runs Scored")
    plt.ylabel("Bowler")
    plt.savefig(os.path.join(save,"Top_Economical_Bowlers.png"),dpi=300)
    plt.show()
    top_bowlerex = (file1.groupby("bowler")["total_runs"].sum().sort_values(ascending=False).reset_index().head(5))
    sns.barplot(data=(top_bowlerex),y="bowler",x="total_runs",hue="bowler",palette="viridis")
    plt.title("Top 5 Most Expensive Bowlers In IPL")
    plt.xlabel("Runs Scored")
    plt.ylabel("Bowler")
    plt.savefig(os.path.join(save,"Top_Expensive_Bowlers.png"),dpi=300)
    plt.show()
    topb=file1["bowler"].value_counts().head(10).index
    sns.countplot(data=file1[file1["bowler"].isin(topb)],y="bowler",order=topb,hue="bowler",legend=False,palette="viridis")
    plt.title("Top 10 Bowlers Who Played Most Of The Balls In IPL")
    plt.xlabel("Balls Played")
    plt.ylabel("Bowler")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Top_Bowlers.png"),dpi=300)
    plt.show()
def Team_Analysis():
    sns.set_style("whitegrid")
    plt.figure(figsize=(10,8))
    sns.countplot(data=file2,y="toss_winner",hue="toss_decision",palette="viridis")
    plt.title("Teams And Toss Decisions")
    plt.xlabel("No. Of Tosses Won")
    plt.ylabel("Team")
    plt.legend(title="Decision")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Team_Toss_Decision.png"),dpi=300)
    plt.show()
def Comparative_Analysis():
    plt.figure(figsize=(10,8))
    file2["toss_winner_won_match"] = file2["toss_winner"] == file2["winner"]
    sns.countplot(data=file2,x="toss_decision",hue="toss_winner_won_match",palette=["#D32F2F", "#2E7D32"])
    plt.title("Victory-Toss Decision Chart")
    plt.ylabel("No. Of Matches Won")
    plt.xlabel("Toss Decision")
    plt.legend(title="Won Both Match And Toss ?")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"victories-Toss_Decision.png"),dpi=300)
    plt.show()
    sns.set_style("whitegrid")
    plt.figure(figsize=(10,8))
    tops=file2["venue"].value_counts().head(10).index
    sns.countplot(data=file2[file2["venue"].isin(tops)],y="venue",hue="toss_decision",order=tops,palette="viridis")
    plt.title("Toss Decisions in Top 10 IPL Stadiums")
    plt.xlabel("No. Of Matches ")
    plt.ylabel("Stadium")
    plt.legend(title="Decision")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Stadium-Toss_Decision.png"),dpi=300)
    plt.show()
    tops5=file2["venue"].value_counts().head(5).index
    plt.figure(figsize=(10,8))
    sns.countplot(data=file2[file2["venue"].isin(tops5)],y="venue",hue="winner",order=tops5,palette="viridis")
    plt.title("Most Common Winner Teams In Top 5 IPL Stadiums")
    plt.xlabel("No. Of Victories")
    plt.ylabel("Stadium")
    plt.legend(title="Winning Team")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Stadium-Winner_Team.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    top5=file2["Season"].value_counts().head(5).index
    sns.countplot(data=file2[file2["Season"].isin(top5)],y="Season",hue="winner",order=top5,palette="viridis")
    plt.title("Most Common Winner Teams in Top 5 IPL Seasons")
    plt.xlabel("No. Of Victories")
    plt.legend(title="Winning Team")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Season-Winner_Team.png"),dpi=300)
    plt.show()
Data_Assessment()
Match_Analysis()
Batting_Analysis()
Bowling_Analysis()
Team_Analysis()
Comparative_Analysis()