import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
file1=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\deliveries.csv")
file2=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\matches.csv")
script_dir=os.path.dirname(os.path.abspath(__file__))
save=os.path.join(script_dir,"Graphs_And_Charts")
if not os.path.exists(save):os.makedirs(save)
def Data_Assessment():
    print(file1.dtypes)
    print(file2.dtypes)
    print(file1.head())
    print(file2.head())
    print(file1.isnull().sum()) #Null values present in player_dismissed,dismissal_kind and fielder.
    print(file2.isnull().sum()) #Null values present in city,winner,umpire1,umpire2,umpire3.
    print(file1[file1.duplicated()]) #No Major duplicates out of more than 20000 matches few coincidences can be neglected.
    print(file2[file1.duplicated()]) #No Duplicates at all.
def Match_Analysis():
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    lock=file2["winner"].value_counts().head(14).index
    sns.countplot(data=file2[file2["winner"].isin(lock)],y="winner",hue="winner",order=lock,palette="viridis",legend=False)
    plt.title("IPL Teams That Have Won Most Of The Matches")
    plt.xlabel("No. Of Matches Won")
    plt.ylabel("Team")
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    lock1=file2["venue"].value_counts().index
    sns.countplot(data=file2[file2["venue"].isin(lock1)],y="venue",order=lock1,color="darkcyan")
    plt.title("Stadium That Have Hosted Highest No. Of Matches")
    plt.xlabel("No. Of Matches Played")
    plt.ylabel("Stadium")
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    top7=file2["player_of_match"].value_counts().head(7).index
    sns.countplot(data=file2[file2["player_of_match"].isin(top7)],x="player_of_match",order=top7,color="yellow")
    plt.title("Top 7 Players With Highest No. Of Player Of The Match Titles")
    plt.ylabel("No. Of Times Player Of The Match Awarded")
    plt.xlabel("Player")
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    file2["toss_match_same"] = file2["toss_winner"] == file2["winner"]
    count=file2["toss_winner"].value_counts().head(14).index
    sns.countplot(data=file2[file2["toss_winner"].isin(count)],y="toss_winner",order=count,hue="toss_match_same",palette="mako")
    plt.title("Toss Winner - Match Winner Connection Chart")
    plt.xlabel("No. Of Matches")
    plt.ylabel("Team")
    plt.legend(bbox_to_anchor=(1,0.5),title="Won Both Match And Toss ?",loc="upper left")
    plt.tight_layout()
    plt.show()
    count1=file2["Season"].value_counts().index
    sns.countplot(data=file2[file2["Season"].isin(count1)],y="Season",order=count1,color="turquoise")
    plt.title("IPL Seasons With Most Matches")
    plt.xlabel("No. Of Matches")
    plt.ylabel("IPL Season")
    plt.tight_layout()
    plt.show()
def Batting_Analysis():
    plt.figure(figsize=(10,8))
    top_batsmen = (file1.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).reset_index().head(5))
    sns.barplot(data=(top_batsmen),y="batsman",x="batsman_runs",hue="batsman",palette="viridis")
    plt.title("Top 10 Run Scorers In IPL")
    plt.xlabel("Runs Scored")
    plt.ylabel("Batsman")
    plt.show()
    plt.figure(figsize=(10,8))
    file1["sixes"]=file1["batsman_runs"]==6
    six_hitters=(file1.groupby("batsman")["sixes"].sum().sort_values(ascending=False).head(10))
    sns.barplot(data=(six_hitters.reset_index()),y="batsman",x="sixes",hue="batsman",palette="viridis")
    plt.title("Top 10 Six Hitters In IPL")
    plt.xlabel("No. Of Sixes")
    plt.ylabel("Batsman")
    plt.show()
    plt.figure(figsize=(10,8))
    file1["fours"]=file1["batsman_runs"]==4
    four_hitters=(file1.groupby("batsman")["fours"].sum().sort_values(ascending=False).head(10))
    sns.barplot(data=(four_hitters.reset_index()),y="batsman",x="fours",hue="batsman",palette="viridis")
    plt.title("Top 10 Four Hitters In IPL")
    plt.xlabel("No. Of Fours")
    plt.ylabel("Batsman")
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=(10,8))
    topb=file1["batsman"].value_counts().head(10).index
    sns.countplot(data=file1[file1["batsman"].isin(topb)],y="batsman",order=topb,hue="batsman",palette="viridis")
    plt.title("Top 10 Batsman Who Have Faced Highest No. Of Balls In IPL")
    plt.xlabel("NO. Of Balls")
    plt.ylabel("Batsman")
    plt.tight_layout()
    plt.show()
def Team_Analysis():
    plt.figure(figsize=(10,8))
    sns.countplot(data=file2,y="toss_winner",hue="toss_decision",palette="viridis")
    plt.title("Teams And Toss Decisions")
    plt.xlabel("No. Of Tosses Won")
    plt.ylabel("Team")
    plt.legend(title="Decision")
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=(10,8))
    sns.countplot(data=file2,y="winner",hue="toss_decision",palette="viridis")
    plt.title("Victories And Toss Decisions")
    plt.xlabel("No. Of Victories")
    plt.ylabel("Team")
    plt.legend(title="Decision")
    plt.tight_layout()
    plt.show()

Data_Assessment()
Match_Analysis()
Batting_Analysis()
Team_Analysis()